server:
  port: 8082
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: group1
          destination: messageQueue
          spring.cloud.stream.bindings.input.content-type: application/x-java-object;type=Greetings
          binder: kafka