server:
  port: 8083
spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 172.28.7.35:2181
          brokers: 172.28.7.35:9092
          autoCreateTopics: true
      bindings:
        input:
          group: group2
          destination: messageQueue
          spring.cloud.stream.bindings.input.content-type: application/x-java-object;type=Greetings
          binder: kafka
          consumer:
            autoCommitOffset: false

